import Api from '../../config/Api'

export const SIGNINAPI = Api.login;
export const SIGNINFETCH = 'SIGNINFETCH';
export const SIGNINSUCCESS = 'SIGNINSUCCESS';
export const SIGNINFAILED = 'SIGNINFAILED';

export const USERPROFILEAPI = Api.userProfile;
export const USERPROFILEFETCH = 'USERPROFILEFETCH';
export const USERPROFILESUCCESS = 'USERPROFILESUCCESS';
export const USERPROFILEFAILED = 'USERPROFILEFAILED';

export const USERPROFILEUPDATEAPI = Api.userUpdate;
export const USERPROFILEUPDATEFETCH = 'USERPROFILEUPDATEFETCH';
export const USERPROFILEUPDATESUCCESS = 'USERPROFILEUPDATESUCCESS';
export const USERPROFILEUPDATEFAILED = 'USERPROFILEUPDATEFAILED';

export const DIVISIAPI = Api.divisi;
export const DIVISIFETCH = 'DIVISIFETCH';
export const DIVISISUCCESS = 'DIVISISUCCESS';
export const DIVISIFAILED = 'DIVISIFAILED';

export const STATUSAPI = Api.status;
export const STATUSFETCH = 'STATUSFETCH';
export const STATUSSUCCESS = 'STATUSSUCCESS';
export const STATUSFAILED = 'STATUSFAILED';

export const LOGOUT = {
  FETCH: 'LOGOUT_FETCH',
  SUCCESS: 'LOGOUT_SUCCESS',
  FAILED: 'LOGOUT_FAILED'
}